### PR TITLE
Adding connection details for AWS hosted ES

### PR DESCRIPTION
**Pull request by nelsonSchwarz**
Easy access in README for people just starting to query ES.

### CODE REVIEW

**Comment by sckott** [comment]
thanks @nelsonSchwarz !

I assume this is related to http://stackoverflow.com/questions/40895027/connecting-to-aws-elasticsearch-service-using-r-getting-404-error 

Can you make the edits in the `README.Rmd` and `README.md` files please

**Comment by nelsonSchwarz** [comment]
Sure. I'll make the same changes to the .Rmd file

**Comment by sckott** [comment]
@nelsonSchwarz  Hmm, looks like you've opened a new PR, I meant to add the change to `README.md` to this PR

**Comment by sckott** [comment]
you can just make new commits to the same branch

**Comment by nelsonSchwarz** [comment]
Oh... I'm sorry. I don't know how to do that. It's my first time requesting a pull...

**Comment by nelsonSchwarz** [comment]
Oh ok, should I close the previous PR and make the same commits here?

**Comment by sckott** [comment]
No problem at all. Yes, add the readme.rmd change to this PR,

**Comment by sckott** [comment]
if you're using the web interface, just change the file in your version at https://github.com/nelsonSchwarz/elastic/tree/patch-1

**Comment by nelsonSchwarz** [comment]
Now it should be correct.

**Comment by sckott** [comment]
thanks very much!

**Pull request merged**
